# Generated by Django 4.2.2 on 2023-08-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('mbti', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('nfid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=500)),
                ('review_key1', models.CharField(max_length=20)),
                ('review_key2', models.CharField(max_length=20)),
                ('review_key3', models.CharField(max_length=20)),
                ('movie_poster', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='nickname',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conv_id', models.ForeignKey(db_column='conv_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('good', models.BooleanField()),
                ('conv_id', models.ForeignKey(db_column='conv_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='movie_recommendation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nfid', models.ForeignKey(db_column='nfid', on_delete=django.db.models.deletion.CASCADE, to='chatbot.movie')),
                ('reco_id', models.ForeignKey(db_column='reco_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.recommendation')),
            ],
        ),
    ]
