# Generated by Django 4.2.2 on 2023-08-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversation_id_alter_movie_recommendation_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nickname',
        ),
    ]
